### ISSUE TITLE
Question: What is the benefit of having this kind of template?

### ISSUE THREAD

**Issue by sherry-ummen** [bradyholt/aspnet-core-react-template#9]
Hi,

I was also wondering about the benefit of having this kind of setup?

Its possible to do UI development independently and then APS.Net Core Web API sperately, and just call the API's from UI end. So I think I am missing lot of things to understand the benefit. Could you please explain a bit?

Thanks

**Comment by bradyholt** [comment]
I don't think I fully understand your question but I *think* you are asking about the benefit of having the UI and API all in the same project rather than having independent projects for each.  Logically, they are two separate pieces of the application and you could physically separate them but I find this to be cumbersome in practice so I prefer to keep them coupled in the same project but still isolated by directory.  But yes, they are different.  If I were to app a mobile client to use the same API, I would probably use a completely different repository for that.
